### ISSUE TITLE
Ask for ZeroFlow 2x weight

### ISSUE THREAD

**Issue by Kin-Zhang** [kylevedder/zeroflow_weights#1]
Thanks again for your work! To Kyle.

Could I ask for ZeroFlow 2x weight for me to do an ablation study? Thanks!

**Comment by kylevedder** [comment]
The only 2x setup we trained was the 2x "diverse" (the AV2 LiDAR split from the 3x training run)

Those weights are here:
https://github.com/kylevedder/zeroflow_weights/tree/master/argo/nsfp_distillation_diverse_2x

At one point I erroneously labeled the configs for the 3x as 2x, but I never actually trained a 2x model.

**Comment by Kin-Zhang** [comment]
AHa, good to know still. Thanks!
